version: '3'

services:
  web-service:
    build: .
    ports:
      - "10000:10000"  # Expose Webmin on port 10000
      - "8081:80"      # Expose Apache on port 8081
    volumes:
      - tor-data:/var/lib/tor
    networks:
      - tor-network
    restart: always  # Ensure the container restarts automatically

networks:
  tor-network:
    driver: bridge

volumes:
  tor-data:
